### ISSUE TITLE
Stuck on "GLOBED: Preloading wave/ufo icons"

### ISSUE THREAD

**Issue by Hanuko33** [dankmeme01/globed2#125] opened 2024-03-10 12:39 UTC
title explains everythigns, logs don't tell anything, crashlog doesn't get generated

last line in log is:
(TIME) DEBUG [Main] [Globed]: preloading assets

so yeh, also this bug is introduced in the newest update (v1.3.2)

How to reproduce:
Launch game with globed installed.

**Comment by Hanuko33** [comment] 2024-03-10 12:43
Now it's stuck on other icons

**Comment by Hanuko33** [comment] 2024-03-10 12:56
Ok, so I got the thing working, but now I stumpled upon another bug (that is very bad)

so basically after I get geode working with proton 7.0-6 and joined a lvl, it was shown for a split second, but then it crashed

I thought that the issue was proton 7.0-6, so I ran the game again, disabled preload icons, and ran the game on proton experimental. Sadly the same thing happen. 

The good part is that it generated some logs, so have fun ig:
[2024-03-10_13-51-18.log](https://github.com/dankmeme01/globed2/files/14550220/2024-03-10_13-51-18.log)
[Geode 2024-03-10 13.50.58.log](https://github.com/dankmeme01/globed2/files/14550221/Geode.2024-03-10.13.50.58.log)

**Comment by dankmeme01** [comment] 2024-03-10 19:34
are you sure this is a globed issue? in your crashlog there is nothing about globed, so it's hard for me to tell what's the issue here

**Comment by Hanuko33** [comment] 2024-03-11 18:24
No that sure.
But it happens, when I disable globed, it works, so yeh it would make sense

**Comment by RuralAnemone** [comment] 2024-03-12 23:15
+1, although no version of proton works for me. the only solution I've found is disabling preloading.

**Comment by RuralAnemone** [comment] 2024-03-12 23:16
it's probably a proton issue though
but I'll see what I can find

**Comment by dankmeme01** [comment] 2024-03-13 17:21
can you send your crashlogs too, if you have any? i tried various versions of proton and it seems to work just fine on my machine

**Comment by RuralAnemone** [comment] 2024-03-16 21:03
| proton version | behavior |
|-----------------------|---------------|
| hotfix | hangs on preloading ufo |
| 3.7-8 thru 4.11-13 | GD doesn't launch |
| 5.0-10 | GD doesn't launch but faster this time |
| 5.13-6 and 6.3-8 | crashes after preloading wave, no crashlogs generated |
| 7.0-6 | crashes after proloading other, generates [crash](https://github.com/dankmeme01/globed2/files/14625230/2024-03-16_15-48-43.log) [logs](https://github.com/dankmeme01/globed2/files/14625232/2024-03-16_15-50-10.log)!!! |
| 8.0-5 | hangs on preloading wave, no crashlogs |
| 9.0 (beta) | stuck on downloading content? probably a skill issue |
| experimental | hangs on preloading wave, no crashlogs |

**Comment by RuralAnemone** [comment] 2024-03-16 21:18
steam logs on proton experimental:
https://asciinema.org/a/pS4NafXB6Onpgp9wMWFCtRMQk

**Comment by RuralAnemone** [comment] 2024-03-17 01:01
oh also here's the general Geode log
[Geode 2024-03-10 16.08.19.log](https://github.com/dankmeme01/globed2/files/14625736/Geode.2024-03-10.16.08.19.log)

**Comment by dankmeme01** [comment] 2024-03-17 15:37
unfortunately the crashlog from proton 7 doesn't provide any useful information, and i am still unable to reproduce any of those results myself.

although, hangs on proton 8 and higher are a bug in Wine as far as i'm aware (that will be fixed in Wine 9.5, and subsequently, one of the next Proton Experimental releases). the game does crash (and it does crash due to Globed), but the Geode crash handler code is stuck in a loop, hence the hang.

if you could disable all mods and try to get a crashlog on proton 7 with only globed, it could be helpful, although unlikely.

**Comment by RuralAnemone** [comment] 2024-03-17 16:10
same thing

[Geode 2024-03-17 11.09.02.log](https://github.com/dankmeme01/globed2/files/14628032/Geode.2024-03-17.11.09.02.log)
[2024-03-17_11-09-09.log](https://github.com/dankmeme01/globed2/files/14628033/2024-03-17_11-09-09.log)

**Comment by Hanuko33** [comment] 2024-03-20 17:54
I think the preloading is fixed, but joining any level, instantly crashes the game

**Comment by dankmeme01** [comment] 2024-07-06 09:32
closing as stale, please make a new issue if this still happens on the latest version

**Closed by dankmeme01** 2024-07-06 09:32 UTC
