### ISSUE TITLE
Crash in Editor [Windows 10]

### ISSUE THREAD

**Issue by Brittank88** [dankmeme01/globed2#169] opened 2024-05-24 10:08 UTC
Not sure why this happened but here's the crash log:
[2024-05-24_20-06-15.log](https://github.com/dankmeme01/globed2/files/15431829/2024-05-24_20-06-15.log)

**Comment by dankmeme01** [comment] 2024-05-26 04:04
Doesn't seem like it's caused by Globed, looks rather random. Is there any way to reproduce the crash or did it happen just once?

**Comment by Brittank88** [comment] 2024-05-26 14:54
Admittedly just happened once - it's just that out of all the crashes I've ever had, I've never seen Globed in the stack trace until now.

**Comment by dankmeme01** [comment] 2024-05-27 06:19
Judging by the stack trace, the crash happened in GD code, the reason Globed is in the stack trace is because it hooks that specific function that caused the crash. But the specific part of the code that caused the crash is unrelated to Globed and the crash is likely not caused by it (to be honest I've never seen a crash like this so I'm not sure what even *could* be the cause)

Closing the issue unless this happens again (in that case you could reopen it)

**Closed by dankmeme01** 2024-05-27 06:19 UTC
