### ISSUE TITLE
Crash whenever I press V to talk.

### ISSUE THREAD

**Issue by LNLenost** [dankmeme01/globed2#57] opened 2024-02-13 09:23 UTC
pls help!!

**Comment by dankmeme01** [comment] 2024-02-13 10:59
duplicate of #56

**Closed by dankmeme01** 2024-02-13 10:59 UTC

**Comment by LNLenost** [comment] 2024-02-13 14:25
You closed the thread but didn't helpwd me...

**Comment by LNLenost** [comment] 2024-02-13 17:10
these are the logs btw
[Geode 2024-02-13 11.52.02.log](https://github.com/dankmeme01/globed2/files/14269872/Geode.2024-02-13.11.52.02.log)
